[package]
name = "p6"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
common = { version = "0.1.0", path = "../common" }
coz = "0.1.3"

[profile.release]
debug = 1
